const books = [
  {
    id: "book-1",
    title: "The Awakening",
    author: "Kate Chopin",
    year: 1899,
    genre: "Fiction",
    rating: 4.2,
  },
  {
    id: "book-2",
    title: "City of Glass",
    author: "Paul Auster",
    year: 1985,
    genre: "Mystery",
    rating: 4.1,
  },
  {
    id: "book-3",
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki, Sharon Lechter",
    year: 1997,
    genre: "Personal Finance",
    rating: 4.5,
  },
  {
    id: "book-4",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    year: 1960,
    genre: "Fiction",
    rating: 4.8,
  },
  {
    id: "book-5",
    title: "1984",
    author: "George Orwell",
    year: 1949,
    genre: "Dystopian",
    rating: 4.7,
  },
  {
    id: "book-6",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    year: 1925,
    genre: "Classic",
    rating: 4.3,
  },
  {
    id: "book-7",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    year: 2011,
    genre: "History",
    rating: 4.6,
  },
  {
    id: "book-8",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    year: 1951,
    genre: "Fiction",
    rating: 4.0,
  },
  {
    id: "book-9",
    title: "Atomic Habits",
    author: "James Clear",
    year: 2018,
    genre: "Self-help",
    rating: 4.8,
  },
  {
    id: "book-10",
    title: "Brave New World",
    author: "Aldous Huxley",
    year: 1932,
    genre: "Science Fiction",
    rating: 4.2,
  },
  {
    id: "book-11",
    title: "The Alchemist",
    author: "Paulo Coelho",
    year: 1988,
    genre: "Adventure",
    rating: 4.4,
  },
  {
    id: "book-12",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    year: 2011,
    genre: "Psychology",
    rating: 4.5,
  },
  {
    id: "book-13",
    title: "Moby-Dick",
    author: "Herman Melville",
    year: 1851,
    genre: "Adventure",
    rating: 3.9,
  },
];

const db = {
  books,
};

export default db;
